src/Entity/Doctor.php
<?php

namespace App\Entity;

use App\Repository\DoctorRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DoctorRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Doctor
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Patient::class, mappedBy="doctor")
     */
    private $patients;

    public function __construct()
    {
        $this->patients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getDoctorName(): string
    {
        return ucwords('Doc. ' . $this->getFirstName()[0] . '. ' . $this->getSurname());
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist()
     * @return $this
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new DateTime();

        return $this;
    }

    /**
     * @return Collection|Patient[]
     */
    public function getPatients(): Collection
    {
        return $this->patients;
    }

    public function addPatient(Patient $patient): self
    {
        if (!$this->patients->contains($patient)) {
            $this->patients[] = $patient;
            $patient->setDoctor($this);
        }

        return $this;
    }

    public function removePatient(Patient $patient): self
    {
        if ($this->patients->contains($patient)) {
            $this->patients->removeElement($patient);
            // set the owning side to null (unless already changed)
            if ($patient->getDoctor() === $this) {
                $patient->setDoctor(null);
            }
        }

        return $this;
    }
}

src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use App\Service\DateManager;
use App\Service\NumberManager;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PatientRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Patient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="integer")
     */
    private $weight;

    /**
     * @ORM\ManyToOne(targetEntity=Doctor::class, inversedBy="patients")
     * @ORM\JoinColumn(nullable=false)
     */
    private $doctor;

    /**
     * @ORM\Column(type="integer")
     */
    private $limitUp;

    /**
     * @ORM\Column(type="integer")
     */
    private $limitDown;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Award::class, mappedBy="patient", orphanRemoval=true)
     */
    private $awards;

    /**
     * @ORM\OneToMany(targetEntity=Data::class, mappedBy="patient", orphanRemoval=true)
     */
    private $data;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity=OverValue::class, mappedBy="patient", orphanRemoval=true)
     */
    private $overValues;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dadSurname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dadFirstName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dadPhoneNumber;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $momSurname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $momFirstName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $momPhoneNumber;

    /**
     * @ORM\OneToOne(targetEntity=Notification::class, mappedBy="patient", cascade={"persist", "remove"})
     */
    private $notification;

    public function __construct()
    {
        $this->awards = new ArrayCollection();
        $this->data = new ArrayCollection();
        $this->overValues = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getBirthday(): ?DateTime
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAge(): int
    {
        $interval = DateManager::dateIntervalBetweenNowAnd($this->getBirthday());
        return $interval->y;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getDoctor(): ?Doctor
    {
        return $this->doctor;
    }

    public function setDoctor(?Doctor $doctor): self
    {
        $this->doctor = $doctor;

        return $this;
    }

    public function getLimitUp(): ?int
    {
        return $this->limitUp;
    }

    public function setLimitUp(int $limitUp): self
    {
        $this->limitUp = $limitUp;

        return $this;
    }

    public function getLimitDown(): ?int
    {
        return $this->limitDown;
    }

    public function setLimitDown(int $limitDown): self
    {
        $this->limitDown = $limitDown;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist()
     * @return $this
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new DateTime();

        return $this;
    }

    /**
     * @return Collection|Award[]
     */
    public function getAwards(): Collection
    {
        return $this->awards;
    }

    public function addAward(Award $award): self
    {
        if (!$this->awards->contains($award)) {
            $this->awards[] = $award;
            $award->setPatient($this);
        }

        return $this;
    }

    public function removeAward(Award $award): self
    {
        if ($this->awards->contains($award)) {
            $this->awards->removeElement($award);
            // set the owning side to null (unless already changed)
            if ($award->getPatient() === $this) {
                $award->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Data[]
     */
    public function getData(): Collection
    {
        return $this->data;
    }

    public function addData(Data $data): self
    {
        if (!$this->data->contains($data)) {
            $this->data[] = $data;
            $data->setPatient($this);
        }

        return $this;
    }

    public function removeData(Data $data): self
    {
        if ($this->data->contains($data)) {
            $this->data->removeElement($data);
            // set the owning side to null (unless already changed)
            if ($data->getPatient() === $this) {
                $data->setPatient(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|OverValue[]
     */
    public function getOverValues(): Collection
    {
        return $this->overValues;
    }

    public function addOverValue(OverValue $overValue): self
    {
        if (!$this->overValues->contains($overValue)) {
            $this->overValues[] = $overValue;
            $overValue->setPatient($this);
        }

        return $this;
    }

    public function removeOverValue(OverValue $overValue): self
    {
        if ($this->overValues->contains($overValue)) {
            $this->overValues->removeElement($overValue);
            // set the owning side to null (unless already changed)
            if ($overValue->getPatient() === $this) {
                $overValue->setPatient(null);
            }
        }

        return $this;
    }

    public function getDadSurname(): ?string
    {
        return $this->dadSurname;
    }

    public function setDadSurname(?string $dadSurname): self
    {
        $this->dadSurname = $dadSurname;

        return $this;
    }

    public function getDadFirstName(): ?string
    {
        return $this->dadFirstName;
    }

    public function setDadFirstName(?string $dadFirstName): self
    {
        $this->dadFirstName = $dadFirstName;

        return $this;
    }

    public function getDadFullName(): string
    {
        return 'M. ' . $this->dadFirstName . ' ' . strtoupper($this->dadSurname);
    }

    public function getDadPhoneNumber(): ?string
    {
        return $this->dadPhoneNumber;
    }

    public function getDadFormattedPhoneNumber(): string
    {
        return NumberManager::addPointToPhoneNumber($this->getDadPhoneNumber());
    }

    public function setDadPhoneNumber(?string $dadPhoneNumber): self
    {
        $this->dadPhoneNumber = $dadPhoneNumber;

        return $this;
    }

    public function getMomSurname(): ?string
    {
        return $this->momSurname;
    }

    public function setMomSurname(?string $momSurname): self
    {
        $this->momSurname = $momSurname;

        return $this;
    }

    public function getMomFirstName(): ?string
    {
        return $this->momFirstName;
    }

    public function setMomFirstName(?string $momFirstName): self
    {
        $this->momFirstName = $momFirstName;

        return $this;
    }

    public function getMomFullName(): string
    {
        return 'Mme. ' . $this->momFirstName . ' ' . strtoupper($this->momSurname);
    }

    public function getMomPhoneNumber(): ?string
    {
        return $this->momPhoneNumber;
    }

    public function getMomFormattedPhoneNumber(): string
    {
        return NumberManager::addPointToPhoneNumber($this->getMomPhoneNumber());
    }

    public function setMomPhoneNumber(?string $momPhoneNumber): self
    {
        $this->momPhoneNumber = $momPhoneNumber;

        return $this;
    }

    public function getNotification(): ?Notification
    {
        return $this->notification;
    }

    public function setNotification(Notification $notification): self
    {
        $this->notification = $notification;

        // set the owning side of the relation if necessary
        if ($notification->getPatient() !== $this) {
            $notification->setPatient($this);
        }

        return $this;
    }
}

src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('surname', TextType::class, [
                'label' => false,
                'attr'  => ['placeholder' => 'Nom', 'title'=> 'Ajoutez un nom']
            ])
            ->add('firstName', TextType::class, [
                'label' => false,
                'attr'  => ['placeholder' => 'Prénom', 'title'=> 'Ajoutez un prénom']
            ])
            ->add('birthday', BirthdayType::class, [
                'label' => false,
                'widget' => 'single_text',
                'attr'=>['title'=>'ex : 02/12/2019']
            ])
            ->add('weight', IntegerType::class, [
                'label' => false,
                'attr'  => ['placeholder' => 'Poids (kg)', 'title'=> 'ex : 20']
            ])
            ->add('limitUp', IntegerType::class, [
                'label' => false,
                'attr'  => ['placeholder' => 'Seuil haut (mg/dL)', 'title'=> 'ex : 180']
            ])
            ->add('limitDown', IntegerType::class, [
                'label' => false,
                'attr'  => ['placeholder' => 'Seuil bas (mg/dL)', 'title'=> 'ex : 60']
            ])
            ->add('email', TextType::class, [
                'label' => false,
                'attr'=>['title'=>'votrepatient@exemple.com']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

src/Controller/Patient/BadgeController.php
<?php


namespace App\Controller\Patient;


use App\Entity\Badge;
use App\Entity\Data;
use App\Service\BadgeManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class BadgeController extends AbstractController
{
    /**
     * @Route("/check/badge", name="check_badge")
     * @param BadgeManager $badgeManager
     * @param SessionInterface $session
     * @return JsonResponse
     */
    public function checkBadge(BadgeManager $badgeManager, SessionInterface $session): JsonResponse
    {
        $patient = $session->get('patient');

        $data = count($this->getDoctrine()
            ->getRepository(Data::class)
            ->findBy(['patient' => $patient->getId()]));

        $badges = $this->getDoctrine()
            ->getRepository(Badge::class)
            ->findAll();

        $badge = $badgeManager->addBadge($patient, $data, $badges);

        return new JsonResponse($badge);
    }
}

templates/patient/parent.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ patient.firstName | capitalize ~ ' ' ~ patient.surname | upper }}{% endblock %}

{% block body %}
    <input type="hidden" id="PatientId" data-id="{{ patient.id }}">
    <div class="container-fluid bg-light-grey min-vh-100">
        <div class="row">
            {% for category, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ category }} text-center container mt-5">
                        {{ message }}
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
        <div class="row mt-5">
            <div class="col-6 d-flex flex-column">
                <div class="m-auto">
                    <h3><span class="show-icon bg-white text-center mr-3 shadow"><i
                                    class="fas fa-user-injured mt-1"></i></span> {{ patient.firstName| capitalize ~ ' ' ~ patient.surname | upper }}
                    </h3>
                    <h4 class="font-weight-lighter"><span class="show-icon bg-white text-center mr-3 shadow"><i
                                    class="fas fa-birthday-cake mt-1"></i></span> {{ patient.birthday | date ('d/m/Y') }}
                        - {{ patient.age }} ans</h4>
                    <h4 class="font-weight-lighter"><span class="show-icon bg-white text-center mr-3 shadow"><i
                                    class="fas fa-weight mt-1"></i></span> Poids {{ patient.weight }} Kg</h4>
                </div>
            </div>
            <div class="col-6 d-flex flex-column">
                <div class="m-auto">
                    <h4 class="font-weight-lighter"><span class="show-icon bg-white text-center mr-3 shadow"><i
                                    class="fas fa-virus mt-1"></i></span> Diabète Insulino Dépendant</h4>
                    <h4 class="font-weight-lighter"><span class="show-icon bg-white text-center mr-3 shadow"><i
                                    class="fas fa-stethoscope mt-1"></i></span> {{ patient.doctor.doctorName }}</h4>
                    <h4 class="font-weight-lighter"><span class="show-icon bg-white text-center mr-3 shadow"><i
                                    class="fas fa-phone-square mt-1"></i></span> 06.48.32.72.64</h4>
                </div>
            </div>
        </div>

        <hr class="mt-5">

        <div class="d-flex justify-content-center">
            <a class="d-flex flex-column align-items-center text-blue" id="toggle1" data-toggle="collapse"
               href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" title="Cliquer pour afficher">
                <p class="mb-0">Modifier vos coordonnées personnelles</p>
                <p class="mb-0 mt-neg" id="i1"><i class="fas fa-caret-down"></i></p>
            </a>
        </div>
        <div class="collapse" id="collapseExample">
            {{ form_start(contact) }}
            <div class="container bck-grey p-3 mb-3 w-25">
                {{ form_label(contact.email) }}
                {{ form_widget(contact.email) }}
            </div>
            <div class="d-flex justify-content-around container">
                <div class="card parent-card bck-grey" style="width: 30rem;">
                    <div class="card-body">
                        <h2 class="card-subtitle mb-2 text-muted text-center">Père</h2>
                        <div class="d-flex">
                            <div class="col-5">
                                {{ form_label(contact.dadSurname) }}
                                {{ form_label(contact.dadFirstName) }}
                                {{ form_label(contact.dadPhoneNumber) }}
                            </div>
                            <div class="col_5 offset_2">
                                {{ form_widget(contact.dadSurname) }}
                                {{ form_widget(contact.dadFirstName) }}
                                {{ form_widget(contact.dadPhoneNumber) }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card parent-card bck-grey" style="width: 30rem;">
                    <div class="card-body">
                        <h2 class="card-subtitle mb-2 text-muted text-center">Mère</h2>
                        <div class="d-flex">
                            <div class="col-5">
                                {{ form_label(contact.momSurname) }}
                                {{ form_label(contact.momFirstName) }}
                                {{ form_label(contact.momPhoneNumber) }}
                            </div>
                            <div class="col_5 offset_2">
                                {{ form_widget(contact.momSurname) }}
                                {{ form_widget(contact.momFirstName) }}
                                {{ form_widget(contact.momPhoneNumber) }}
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary envoyer" title="Cliquez pour envoyer">Envoyer !</button>
            </div>

            {{ form_end(contact) }}
        </div>

        <hr>

        <div class="canvas pb-2">
            <canvas id="glycemia"></canvas>
        </div>
    </div>
{% endblock %}

    {% block javascript %}
    {{ encore_entry_script_tags('glycemia') }}
    {{ encore_entry_script_tags('ajaxNotification') }}
    <script>
        document.getElementById('toggle1').addEventListener('click', (e) => {
        document.getElementById('i1').classList.toggle('rotator')
    })
    </script>
    {% endblock %}