src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use App\Service\DateManager;
use App\Service\NumberManager;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PatientRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Patient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="integer")
     */
    private $weight;

    /**
     * @ORM\ManyToOne(targetEntity=Doctor::class, inversedBy="patients")
     * @ORM\JoinColumn(nullable=false)
     */
    private $doctor;

    /**
     * @ORM\Column(type="integer")
     */
    private $limitUp;

    /**
     * @ORM\Column(type="integer")
     */
    private $limitDown;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Award::class, mappedBy="patient", orphanRemoval=true)
     */
    private $awards;

    /**
     * @ORM\OneToMany(targetEntity=Data::class, mappedBy="patient", orphanRemoval=true)
     */
    private $data;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity=OverValue::class, mappedBy="patient", orphanRemoval=true)
     */
    private $overValues;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dadSurname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dadFirstName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $dadPhoneNumber;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $momSurname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $momFirstName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $momPhoneNumber;

    /**
     * @ORM\OneToOne(targetEntity=Notification::class, mappedBy="patient", cascade={"persist", "remove"})
     */
    private $notification;

    public function __construct()
    {
        $this->awards = new ArrayCollection();
        $this->data = new ArrayCollection();
        $this->overValues = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getBirthday(): ?DateTime
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAge(): int
    {
        $interval = DateManager::dateIntervalBetweenNowAnd($this->getBirthday());
        return $interval->y;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getDoctor(): ?Doctor
    {
        return $this->doctor;
    }

    public function setDoctor(?Doctor $doctor): self
    {
        $this->doctor = $doctor;

        return $this;
    }

    public function getLimitUp(): ?int
    {
        return $this->limitUp;
    }

    public function setLimitUp(int $limitUp): self
    {
        $this->limitUp = $limitUp;

        return $this;
    }

    public function getLimitDown(): ?int
    {
        return $this->limitDown;
    }

    public function setLimitDown(int $limitDown): self
    {
        $this->limitDown = $limitDown;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist()
     * @return $this
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new DateTime();

        return $this;
    }

    /**
     * @return Collection|Award[]
     */
    public function getAwards(): Collection
    {
        return $this->awards;
    }

    public function addAward(Award $award): self
    {
        if (!$this->awards->contains($award)) {
            $this->awards[] = $award;
            $award->setPatient($this);
        }

        return $this;
    }

    public function removeAward(Award $award): self
    {
        if ($this->awards->contains($award)) {
            $this->awards->removeElement($award);
            // set the owning side to null (unless already changed)
            if ($award->getPatient() === $this) {
                $award->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Data[]
     */
    public function getData(): Collection
    {
        return $this->data;
    }

    public function addData(Data $data): self
    {
        if (!$this->data->contains($data)) {
            $this->data[] = $data;
            $data->setPatient($this);
        }

        return $this;
    }

    public function removeData(Data $data): self
    {
        if ($this->data->contains($data)) {
            $this->data->removeElement($data);
            // set the owning side to null (unless already changed)
            if ($data->getPatient() === $this) {
                $data->setPatient(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|OverValue[]
     */
    public function getOverValues(): Collection
    {
        return $this->overValues;
    }

    public function addOverValue(OverValue $overValue): self
    {
        if (!$this->overValues->contains($overValue)) {
            $this->overValues[] = $overValue;
            $overValue->setPatient($this);
        }

        return $this;
    }

    public function removeOverValue(OverValue $overValue): self
    {
        if ($this->overValues->contains($overValue)) {
            $this->overValues->removeElement($overValue);
            // set the owning side to null (unless already changed)
            if ($overValue->getPatient() === $this) {
                $overValue->setPatient(null);
            }
        }

        return $this;
    }

    public function getDadSurname(): ?string
    {
        return $this->dadSurname;
    }

    public function setDadSurname(?string $dadSurname): self
    {
        $this->dadSurname = $dadSurname;

        return $this;
    }

    public function getDadFirstName(): ?string
    {
        return $this->dadFirstName;
    }

    public function setDadFirstName(?string $dadFirstName): self
    {
        $this->dadFirstName = $dadFirstName;

        return $this;
    }

    public function getDadFullName(): string
    {
        return 'M. ' . $this->dadFirstName . ' ' . strtoupper($this->dadSurname);
    }

    public function getDadPhoneNumber(): ?string
    {
        return $this->dadPhoneNumber;
    }

    public function getDadFormattedPhoneNumber(): string
    {
        return NumberManager::addPointToPhoneNumber($this->getDadPhoneNumber());
    }

    public function setDadPhoneNumber(?string $dadPhoneNumber): self
    {
        $this->dadPhoneNumber = $dadPhoneNumber;

        return $this;
    }

    public function getMomSurname(): ?string
    {
        return $this->momSurname;
    }

    public function setMomSurname(?string $momSurname): self
    {
        $this->momSurname = $momSurname;

        return $this;
    }

    public function getMomFirstName(): ?string
    {
        return $this->momFirstName;
    }

    public function setMomFirstName(?string $momFirstName): self
    {
        $this->momFirstName = $momFirstName;

        return $this;
    }

    public function getMomFullName(): string
    {
        return 'Mme. ' . $this->momFirstName . ' ' . strtoupper($this->momSurname);
    }

    public function getMomPhoneNumber(): ?string
    {
        return $this->momPhoneNumber;
    }

    public function getMomFormattedPhoneNumber(): string
    {
        return NumberManager::addPointToPhoneNumber($this->getMomPhoneNumber());
    }

    public function setMomPhoneNumber(?string $momPhoneNumber): self
    {
        $this->momPhoneNumber = $momPhoneNumber;

        return $this;
    }

    public function getNotification(): ?Notification
    {
        return $this->notification;
    }

    public function setNotification(Notification $notification): self
    {
        $this->notification = $notification;

        // set the owning side of the relation if necessary
        if ($notification->getPatient() !== $this) {
            $notification->setPatient($this);
        }

        return $this;
    }
}

src/Controller/Doctor/DoctorController.php
<?php

namespace App\Controller\Doctor;

use App\Entity\Notification;
use App\Entity\Patient;
use App\Form\PatientLimitType;
use App\Form\PatientType;
use App\Repository\DoctorRepository;
use App\Repository\PatientRepository;
use App\Service\MailingService;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\DataRepository;
use App\Service\DataManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DoctorController extends AbstractController
{
    const NUMBER_OF_DATA = 21; // 7jours

    /**
     * @Route("/doctor", name="doctor")
     * @param Request $request
     * @param PatientRepository $patientRepository
     * @param DoctorRepository $doctorRepository
     * @return Response
     */
    public function index(Request $request, PatientRepository $patientRepository, DoctorRepository $doctorRepository)

    {
        $patient = new Patient();
        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $patient->setDoctor($doctorRepository->findOneBy(['id' => 1]));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($patient);
            $entityManager->flush();
            $this->addFlash('success', $patient->getFirstName() . ' a bien été ajouté ');

            return $this->redirectToRoute('doctor');
        }
        return $this->render('doctor/index.html.twig', [
            'patients' => $patientRepository->findBy([], ['surname' => 'ASC']),
            'form' => $form->createView(),
            'doctor' => $doctorRepository->findOneBy(['surname' => 'Olib']),
        ]);
    }

    /**
     * @Route("/doctor/patient/{id}", name="doctor_patient", methods={"GET", "POST"})
     * @param Patient $patient
     * @param Request $request
     * @param PatientRepository $patientRepository
     * @return Response
     */
    public function showAndEditPatient(Patient $patient, Request $request, PatientRepository $patientRepository)
    {
        $form = $this->createForm(PatientLimitType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'Les données de ' . $patient->getFirstName() . ' ont été mises à jour');

            return $this->redirectToRoute('doctor_patient', ['id' => $patient->getId()]);
        }

        return $this->render('doctor/patient/show.html.twig', [
            'choosenPatient' => $patient,
            'patients' => $patientRepository->findBy([], ['surname' => 'ASC']),
            'form' => $form->createView()]);
    }

    /**
     * @Route("/doctor/fetchData/{id}", name="fetch_data")
     * @param Patient $patient
     * @param DataRepository $dataRepository
     * @param DataManager $dataManager
     * @return JsonResponse
     */
    public function fetchData(Patient $patient, DataRepository $dataRepository, DataManager $dataManager): JsonResponse
    {
        $beforeEat = $dataRepository->findBy(['patient' => $patient, 'hasEaten' => false], ['addedAt' => 'DESC'], self::NUMBER_OF_DATA);
        $beforeEat = $dataManager->prepareDataForGraphic($beforeEat);

        $afterEat = $dataRepository->findBy(['patient' => $patient, 'hasEaten' => true], ['addedAt' => 'DESC'], self::NUMBER_OF_DATA);
        $afterEat = $dataManager->prepareDataForGraphic($afterEat);

        $threshold['min'] = $patient->getLimitDown();
        $threshold['max'] = $patient->getLimitUp();

        return new JsonResponse([
            'beforeEat' => $beforeEat,
            'afterEat' => $afterEat,
            'threshold' => $threshold
        ]);
    }

    /**
     * @Route("/doctor/email/send", name="doctor_email")
     * @param Request $request
     * @param MailingService $mailingService
     * @param PatientRepository $patientRepository
     */
    public function doctorSendMail(Request $request, MailingService $mailingService, PatientRepository $patientRepository)
    {
        if ($request->request->has('subject')) {
            if ($request->files->has('files')) {
                $brochureFile = $request->files->get('files');
                $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = str_replace(' ', '', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$brochureFile->guessExtension();
                $notification = new Notification();
                $patient = $patientRepository->findOneBy(['id' => $request->request->get('id')]);
                $notification->setHasNotification(true);
                $notification->setPatient($patient);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($notification);
                $entityManager->flush();

                try {
                    $brochureFile->move(
                        $this->getParameter('files_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Erreur interne');
                }
                $this->addFlash('success', 'Votre email a été envoyé avec succès');

                $mailingService->emailToParents($request->request, $newFilename);

                return $this->redirectToRoute('doctor_patient', ['id' => $request->request->get('id')]);
            }
        }
    }
}

src/Controller/Patient/BadgeController.php
<?php


namespace App\Controller\Patient;


use App\Entity\Badge;
use App\Entity\Data;
use App\Service\BadgeManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class BadgeController extends AbstractController
{
    /**
     * @Route("/check/badge", name="check_badge")
     * @param BadgeManager $badgeManager
     * @param SessionInterface $session
     * @return JsonResponse
     */
    public function checkBadge(BadgeManager $badgeManager, SessionInterface $session): JsonResponse
    {
        $patient = $session->get('patient');

        $data = count($this->getDoctrine()
            ->getRepository(Data::class)
            ->findBy(['patient' => $patient->getId()]));

        $badges = $this->getDoctrine()
            ->getRepository(Badge::class)
            ->findAll();

        $badge = $badgeManager->addBadge($patient, $data, $badges);

        return new JsonResponse($badge);
    }
}

templates/doctor/patient/_edit_limit_form.html.twig
{{ form_start(form) }}
<div class="mt-4">
    {{ form_label(form.weight) }}
    {{ form_widget(form.weight) }}
</div>
<div class="mt-4">
    {{ form_label(form.limitDown) }}
    {{ form_widget(form.limitDown) }}
</div>
<div class="mt-4">
    {{ form_label(form.limitUp) }}
    {{ form_widget(form.limitUp) }}
</div>

<button class="btn btn-primary mt-3 float-right mr-4" title="Cliquez pour modifier">{{ button_label|default('Modifier !') }}</button>

{{ form_end(form) }}

templates/doctor/patient/_form.html.twig
{{ form_start(form) }}
    <div class="mt-4">
        {{ form_label(form.surname) }}
        {{ form_widget(form.surname) }}

    {{ form_label(form.firstName) }}
    {{ form_widget(form.firstName) }}
</div>
<div class="mt-4">
    {{ form_label(form.birthday) }}
    {{ form_widget(form.birthday) }}
</div>
<div class="mt-4">
    {{ form_label(form.weight) }}
    {{ form_widget(form.weight) }}
</div>
<div class="mt-4">
    {{ form_label(form.limitUp) }}
    {{ form_widget(form.limitUp) }}

    {{ form_label(form.limitDown) }}
    {{ form_widget(form.limitDown) }}
</div>

<button class="btn btn-outline-primary mt-5">{{ button_label|default('Ajouter !') }}</button>

{{ form_end(form) }}

templates/doctor/patient/_form_edit_limit.html.twig
{{ form_start(form) }}
<div class="mt-4">
    {{ form_label(form.weight) }}
    {{ form_widget(form.weight) }}
</div>
<div class="mt-4">
    {{ form_label(form.limitDown) }}
    {{ form_widget(form.limitDown) }}
</div>
<div class="mt-4">
    {{ form_label(form.limitUp) }}
    {{ form_widget(form.limitUp) }}
</div>

<button class="btn btn-outline-primary mt-5">{{ button_label|default('Modifier !') }}</button>

{{ form_end(form) }}

templates/doctor/patient/_new_form.html.twig
{{ form_start(form) }}
<div class="d-flex justify-content-around new-form">
    <div>
        <p class="d-inline"><i class="fas fa-child mr-2 loopy-color-darken"></i></p>
        {{ form_widget(form.surname, {'attr': {'class': 'width ml-1'}}) }}
    </div>
    <div>
        <p class="d-inline"><i class="fas fa-child mr-2 loopy-color-darken"></i></p>
        {{ form_widget(form.firstName, {'attr': {'class': 'width ml-1'}}) }}
    </div>
</div>
<div class="mt-4 d-flex justify-content-around">
    <div>
        <p class="d-inline"><i class="fas fa-birthday-cake mr-2 loopy-color-darken"></i></p>
        {{ form_widget(form.birthday, {'attr': {'class': 'width ml-3'}}) }}
    </div>
    <div>
        <p class="d-inline"><i class="fas fa-weight mr-2 loopy-color-darken"></i></p>
        {{ form_widget(form.weight, {'attr': {'class': 'width ml-3'}}) }}
    </div>
</div>
<div class="mt-4 d-flex justify-content-around">
    <div>
        <p class="d-inline"><i class="fas fa-chart-line mr-2 loopy-color-darken"></i></p>
        {{ form_widget(form.limitDown, {'attr': {'class': 'width ml-3'}}) }}
    </div>
    <div>
        <p class="d-inline"><i class="fas fa-chart-line mr-2 loopy-color-darken"></i></p>
        {{ form_widget(form.limitUp, {'attr': {'class': 'width ml-3'}}) }}
    </div>
</div>
{{ form_widget(form.email, {'attr': {'hidden' : 'hidden', 'value' : 'toto@loopy.fr'}}) }}
<button class="btn btn-primary mt-4" title="Cliquez pour ajouter">{{ button_label|default('Ajouter !') }}</button>
{{ form_end(form) }}

templates/doctor/patient/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Loopy | {{ choosenPatient.firstName| capitalize ~ ' ' ~ choosenPatient.surname |upper }}{% endblock %}

{% block body %}
    <input type="hidden" id="PatientId" data-id="{{ choosenPatient.id }}">
    <div class="font-oswald">
        <div class="d-flex">

            <div class="col-9 pt-5 bg-light-grey overflow">
                {% for category, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="alert alert-{{ category }} text-center container mt-5">
                            {{ message }}
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        </div>
                    {% endfor %}
                {% endfor %}

                <div class="d-flex justify-content-around">
                    <div class="d-flex flex-column justify-content-around">
                        <h3 class="d-flex align-items-center"><span
                                    class="show-icon bg-white text-center mr-3 shadow"><i
                                        class="fas fa-user-injured "></i></span> {{ choosenPatient.firstName| capitalize ~ ' ' ~ choosenPatient.surname | upper }}
                        </h3>
                        <h4 class="font-weight-lighter d-flex align-items-center"><span
                                    class="show-icon bg-white text-center mr-3 shadow"><i
                                        class="fas fa-birthday-cake pt-1"></i></span>{{ choosenPatient.birthday | date ('d/m/Y') }}
                            - {{ choosenPatient.age }} ans</h4>
                        <h4 class="font-weight-lighter d-flex align-items-center"><span
                                    class="show-icon bg-white text-center mr-3 shadow"><i class="fas fa-virus pt-1"></i></span>
                            Diabète Insulino Dépendant</h4>
                    </div>
                    {{ include('/doctor/patient/_edit_limit_form.html.twig') }}
                </div>

                {% if choosenPatient.dadSurname or choosenPatient.momSurname %}
                    <hr>

                    <div class="d-flex justify-content-center">
                        <a class="d-flex flex-column align-items-center text-blue" id="toggle1" data-toggle="collapse"
                           href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" title="Cliquer pour afficher">
                            <p class="mb-0">Parents</p>
                            <p class="mb-0 mt-neg" id="i1"><i class="fas fa-caret-down"></i></p>
                        </a>
                        <a class="d-flex flex-column align-items-center ml-5 text-blue" id="toggle2"
                           data-toggle="collapse"
                           href="#collapseEmail" role="button" aria-expanded="false" title="Cliquer pour afficher" aria-controls="collapseExample">
                            <p class="mb-0">Envoyer un email</p>
                            <p class="mb-0 mt-neg" id="i2"><i class="fas fa-caret-down"></i></p>
                        </a>
                    </div>

                    <div class="collapse" id="collapseExample">
                        {% if choosenPatient.dadSurname %}
                        <div class="d-flex justify-content-around container">
                            <div class="card parent-card bck-grey" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-subtitle mb-2 text-muted">Père</h2>
                                    <h5 class="card-title">{{ choosenPatient.dadFullName }}</h5>
                                    <p class="card-text">Téléphone : {{ choosenPatient.dadFormattedPhoneNumber }}</p>
                                </div>
                            </div>
                            {% endif %}
                            {% if choosenPatient.momSurname %}
                                <div class="card parent-card bck-grey" style="width: 18rem;">
                                    <div class="card-body">
                                        <h3 class="card-subtitle mb-2 text-muted">Mère</h3>
                                        <h5 class="card-title">{{ choosenPatient.momFullName }}</h5>
                                        <p class="card-text">Téléphone
                                            : {{ choosenPatient.momFormattedPhoneNumber }}</p>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                <div class="collapse" id="collapseEmail">
                    <div class="d-flex justify-content-center">
                        <form action="{{ path('doctor_email') }}" method="post" enctype="multipart/form-data">
                            <div>
                                <label for="subject"></label>
                                <input type="text" id="subject" name="subject" class="w-100 pl-1 rounded"
                                       placeholder="Objet">
                            </div>
                            <div>
                                <label for="content"></label>
                                <textarea name="content" id="content" cols="30" rows="10" class="w-100 p-1 rounded"
                                          placeholder="Votre mail..."></textarea>
                            </div>
                            <div class="mt-2">
                                <label for="files">Pièce jointe :</label>
                                <input type="file" name="files" id="files">
                            </div>
                            <input type="hidden" name="id" value="{{ choosenPatient.id }}">
                            <button type="submit" class="btn btn-primary mt-2 text-center float-right">Envoyer <i
                                        class="fas fa-check"></i></button>
                        </form>
                    </div>
                </div>
                <hr>

                <h2 class="text-center mt-5">Glycémie sur une semaine</h2>
                <div class="canvas">
                    <canvas id="glycemia"></canvas>
                </div>
            </div>

            <div class="col-3 overflow shadow-list" id="patient-list">
                {% include '/doctor/components/_patient_list.html.twig' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
{{ encore_entry_script_tags('glycemia') }}
{{ encore_entry_script_tags('ajaxValue') }}
<script>
    document.getElementById('toggle1').addEventListener('click', (e) => {
        document.getElementById('i1').classList.toggle('rotator')
    })
    document.getElementById('toggle2').addEventListener('click', (e) => {
        document.getElementById('i2').classList.toggle('rotator')
    })
</script>
{% endblock %}